baseURL = 'https://hyunjae-labs.github.io/'
languageCode = 'ko-kr'
title = 'Hyunjae Blog'
theme = 'PaperMod'

[params]
    author = "hyunjae"
    description = ""
    ShowReadingTime = true
    ShowShareButtons = true
    ShowPostNavLinks = true
    ShowBreadCrumbs = true
    ShowCodeCopyButtons = true
    ShowWordCount = true
    ShowRssButtonInSectionTermList = true
    UseHugoToc = true
    disableSpecial1stPost = false
    disableScrollToTop = false
    comments = false
    hidemeta = false
    hideSummary = false
    showtoc = true
    tocopen = false
    
    # 가독성 개선을 위한 설정
    defaultTheme = "auto"
    disableThemeToggle = false
    ShowFullTextinRSS = true

[params.homeInfoParams]
    Title = ""
    Content = ""

[[params.socialIcons]]
    name = "github"
    url = "https://github.com/hyunjae-labs"

[[params.socialIcons]]
    name = "rss"
    url = "index.xml"

[menu]
  [[menu.main]]
    identifier = "posts"
    name = "Posts"
    url = "/posts/"
    weight = 10
  [[menu.main]]
    identifier = "projects"
    name = "Projects"
    url = "/projects/"
    weight = 20
  [[menu.main]]
    identifier = "about"
    name = "About"
    url = "/about/"
    weight = 30
